const destinationData = [
  {
    country: "France",
    description:
      "France is a diverse and beautiful country known for its rich history, stunning landscapes, and world-famous cuisine. From the romantic streets of Paris to the picturesque lavender fields of Provence, France offers a wide range of travel experiences.",
    language: "French",
    currency: "Euro (EUR)",
    area: "551,695 square kilometers",
    population: "67 million",
    timeZone: "Central European Time (CET)",
    timeToTravel: "Varies based on location and travel method",
    travelSpots: [
      {
        name: "Eiffel Tower",
        title: "The Iron Lady of Paris",
        rating: 4.5,
        reviews: 2500,
        price: "$20 per person",
        timePeriod: "Year-round",
        description: "Iconic landmark in Paris",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
      {
        name: "Louvre Museum",
        title: "Art Lover's Paradise",
        rating: 4.8,
        reviews: 3500,
        price: "$18 per person",
        timePeriod: "Year-round",
        description: "Famous art museum",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
      {
        name: "Versailles Palace",
        title: "Royal Opulence",
        rating: 4.6,
        reviews: 1800,
        price: "$25 per person",
        timePeriod: "Year-round",
        description: "Opulent royal residence",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
      {
        name: "Mont Saint-Michel",
        title: "Magical Island Commune",
        rating: 4.7,
        reviews: 2100,
        price: "$15 per person",
        timePeriod: "Year-round",
        description: "Picturesque island commune",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
      {
        name: "Provence Lavender Fields",
        title: "Scenic Lavender Bliss",
        rating: 4.9,
        reviews: 2800,
        price: "Free",
        timePeriod: "Lavender season in summer",
        description: "Scenic countryside",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
    ],
  },
  {
    country: "Italy",
    description:
      "Italy is a land of ancient history, art, and culture. It's famous for its stunning architecture, world-class cuisine, and beautiful coastal areas. Travelers can explore ancient ruins in Rome, glide through Venice's canals, and savor the flavors of Italian cuisine.",
    language: "Italian",
    currency: "Euro (EUR)",
    area: "301,340 square kilometers",
    population: "60 million",
    timeZone: "Central European Time (CET)",
    timeToTravel: "Varies based on location and travel method",
    travelSpots: [
      {
        name: "Colosseum",
        title: "Ancient Gladiator Arena",
        rating: 4.7,
        reviews: 3000,
        price: "$16 per person",
        timePeriod: "Year-round",
        description: "Ancient amphitheater in Rome",
        image: "https://img.freepik.com/free-photo/beautiful-girl-standing-viewpoint-koh-nangyuan-island-near-koh-tao-island-surat-thani-thailand_335224-1094.jpg?size=626&ext=jpg&ga=GA1.1.1880011253.1699401600&semt=ais",
      },
      {
        name: "Venice Canals",
        title: "Venetian Waterways",
        rating: 4.6,
        reviews: 2600,
        price: "Varies (gondola rides available)",
        timePeriod: "Year-round",
        description: "Famous waterways",
        image: "https://img.freepik.com/free-photo/beautiful-girl-standing-boat-looking-mountains-ratchaprapha-dam-khao-sok-national-park-surat-thani-province-thailand_335224-849.jpg?size=626&ext=jpg&ga=GA1.1.1880011253.1699401600&semt=ais",
      },
      {
        name: "Cinque Terre",
        title: "Colorful Coastal Villages",
        rating: 4.8,
        reviews: 3200,
        price: "Varies (hiking trails available)",
        timePeriod: "Year-round",
        description: "Colorful coastal villages",
        image: "https://www.shutterstock.com/image-photo/traveler-woman-on-tree-branch-260nw-2103096128.jpg",
      },
      {
        name: "Pompeii Ruins",
        title: "Ancient Roman Ghost Town",
        rating: 4.6,
        reviews: 2800,
        price: "$15 per person",
        timePeriod: "Year-round",
        description: "Ancient city destroyed by a volcano",
        image: "pompeii_ruins.jpg",
      },
      {
        name: "Amalfi Coast",
        title: "Stunning Coastal Paradise",
        rating: 4.9,
        reviews: 3500,
        price: "Varies based on accommodations",
        timePeriod: "Year-round",
        description: "Stunning coastal area",
        image: "amalfi_coast.jpg",
      },
    ],
  },
];

module.exports = {
  destinationData,
};
